--------------------------------------------------------------------------------
--
-- Design unit generated by Aldec IP Core Generator, version 10.5.
-- Copyright (c) 1997 - 2018 by Aldec, Inc. All rights reserved.
--
--------------------------------------------------------------------------------
--
-- Created on Thursday 2020-02-06, 11:26:25
--
--------------------------------------------------------------------------------
-- Details:
--		Type: Multiplexer
--		Code style: Case statement
--		Inputs and output width: 24
--		Number of inputs: 2
--		Defalut output bits value '0'
--------------------------------------------------------------------------------

--{{ Section below this comment is automatically maintained
--   and may be overwritten
--{entity {mux} architecture {mux_arch}}

library IEEE;
use IEEE.std_logic_1164.all;

entity mux is
	port (
		I0 : in std_logic_vector(23 downto 0);
		I1 : in std_logic_vector(23 downto 0);
		S : in std_logic;
		O : out std_logic_vector(23 downto 0)
	);
end entity;

--}} End of automatically maintained section

library IEEE;
use IEEE.std_logic_unsigned.all;

architecture mux_arch of mux is
begin

	process (S, I0, I1)
	begin
		if S = '0' then
			 O <= I0;
		else
			 O <= I1;
		end if;
	end process;

end architecture;
